---

- stat: path=~/.rvm
  register: rvm_path
  changed_when: false

- name: Install RVM
  shell: curl -sSL https://get.rvm.io | bash -s stable --ruby
  when: (not rvm_path.stat.exists)

- shell: ~/.rvm/bin/rvm gemdir
  register: rvm_gemdir
  changed_when: false

- lineinfile: dest=~/.zshrc line='export PATH="{{ rvm_gemdir.stdout }}/bin:$PATH"'

- include: install-gem.yml gem=bundler
- include: install-gem.yml gem=compass
