---

- stat: path=~/.oh-my-zsh
  register: zsh_path

- name: install oh-my-zsh
  shell: curl -L http://install.ohmyz.sh | sh
  when: (not zsh_path.stat.exists)

- name: Flow oh-my-zsh plugin
  git: repo=git://github.com/sandstorm/oh-my-zsh-flow3-plugin.git dest=~/.oh-my-zsh/custom/plugins/flow
  when: (not zsh_path.stat.exists)

- name: 'Enable flow plugin'
  lineinfile: dest=~/.zshrc regexp="plugins=\(git\)" line="plugins=(git flow)" backrefs=yes state=present
